AWSTemplateFormatVersion: "2010-09-09"
Description: Infrastructure for CloudFront hosted website

Resources:
  ################
  ## S3 - Start ##
  ################

  s3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: austinengle-resume-s3

  s3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref s3Bucket
      PolicyDocument:
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - Ref: "s3Bucket"
                  - "/*"
            Principal:
              "AWS": !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}"
          - Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - Ref: "s3Bucket"
                  - "/*"
            Principal:
              "AWS": "*"

  ##############
  ## S3 - End ##
  ##############

  ########################
  ## CloudFront - Start ##
  ########################

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: "Resume CloudFront"
        Enabled: True
        DefaultRootObject: index.html
        HttpVersion: http2
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: false
          TargetOriginId: resume-frontend
          ViewerProtocolPolicy: redirect-to-https

        Origins:
          - DomainName: !GetAtt s3Bucket.DomainName
            Id: resume-frontend
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "Access for Resume Frontend"
  ######################
  ## CloudFront - End ##
  ######################
